### ISSUE TITLE
need influxdb help

### ISSUE THREAD

**Issue by grandfatheryun** [Cruzoft/nbminer-reporter#15]
well,i use 2.0 web gui ,and i had make the miner-org and miner bucket
and next i run the bat

C:\Users\yun\Desktop\NBMiner_Win>nbreporter -n test -h 106.53.107.206 -r 12345 -s 192.168.0.9 -v
time="2021-11-26T23:31:08+08:00" level=warning msg="Log level set to DEBUG"
time="2021-11-26T23:31:08+08:00" level=info msg="NBMiner Status Reporter Initiated"
time="2021-11-26T23:31:08+08:00" level=info msg="Using Friendly Name: test"

just this for 30min till i close it,and db no date

**Comment by grandfatheryun** [comment]
Q1 Under win, you need to right-click the cmd window to continue to display
This seems to be a win issue
Q2 
C:\Users\yun\Desktop\NBMiner_Win>nbreporter -n test -h 106.53.107.206 -r 12345 -s 192.168.0.9 -v
time="2021-11-26T23:33:53+08:00" level=warning msg="Log level set to DEBUG"
time="2021-11-26T23:33:53+08:00" level=info msg="NBMiner Status Reporter Initiated"
time="2021-11-26T23:33:53+08:00" level=info msg="Using Friendly Name: test"
time="2021-11-26T23:34:53+08:00" level=info msg="Checking Status."
time="2021-11-26T23:34:53+08:00" level=debug msg="Running GET request to miner status endpoint"
time="2021-11-26T23:34:53+08:00" level=debug msg="Parsing miner status json"
time="2021-11-26T23:34:53+08:00" level=debug msg="Sending data to InfluxDB"
2021/11/26 23:34:54 influxdb2client E! Write error: unauthorized: unauthorized access
time="2021-11-26T23:37:03+08:00" level=error msg="Something when wrong while trying to send data to InfluxDB."
time="2021-11-26T23:37:03+08:00" level=debug msg="Data sent"
time="2021-11-26T23:37:03+08:00" level=info msg="Checking Status."
time="2021-11-26T23:37:03+08:00" level=error msg="Write error: write failed (attempts 0): unauthorized: unauthorized access\n"
time="2021-11-26T23:37:03+08:00" level=debug msg="Running GET request to miner status endpoint"
time="2021-11-26T23:37:03+08:00" level=debug msg="Parsing miner status json"
time="2021-11-26T23:37:03+08:00" level=debug msg="Sending data to InfluxDB"
2021/11/26 23:37:04 influxdb2client E! Write error: unauthorized: unauthorized access
time="2021-11-26T23:37:04+08:00" level=error msg="Something when wrong while trying to send data to InfluxDB."
time="2021-11-26T23:37:04+08:00" level=error msg="Write error: write failed (attempts 0): unauthorized: unauthorized access\n"
time="2021-11-26T23:37:04+08:00" level=debug msg="Data sent"

**Comment by grandfatheryun** [comment]
please add more info about it，for influxdb 2.0 it need make a token for nbminer-reporter
then add -t <token> in the bat, and just run and wait for 1min ,you can see the date in your db

**Comment by ingcsmoreno** [comment]
Thanks a lot @grandfatheryun for your feedback. Yes, I was about to suggest to use the `-t` option, glad you find it.

I've updated the instructions here: https://github.com/Cruzoft/nbminer-reporter/tree/smoreno/influxsetup2#influxdb-setup, let me know what you think.

Regarding the issue about waiting for a minute, that's been already addressed as part of #14 , but hasn't been release yet.

**Comment by grandfatheryun** [comment]
still some question，i can see the reporter make some date in the db，but there is nothing about the tag of value

**Comment by grandfatheryun** [comment]
![image](https://user-images.githubusercontent.com/80371691/143670094-5e2bd37e-8e2b-4130-8b11-a10204d8790d.png)

**Comment by grandfatheryun** [comment]
![image](https://user-images.githubusercontent.com/80371691/143670121-a0d0f4ba-113f-4b3d-9710-636a451b2977.png)

**Comment by ingcsmoreno** [comment]
@grandfatheryun  Glad to see you got it running!

Also, just released a new version with all the fixes we mentioned before, [check it out!](https://github.com/Cruzoft/nbminer-reporter/releases/tag/v1.1.1)
