### ISSUE TITLE
no date input to db

### ISSUE THREAD

**Issue by grandfatheryun** [Cruzoft/nbminer-reporter#20]
please help me to check the problem

![image](https://user-images.githubusercontent.com/80371691/143731986-f8b7f2cb-913c-4b64-8665-4192d2df999a.png)
![image](https://user-images.githubusercontent.com/80371691/143731990-47149b1a-9063-4a20-a284-c54a80c06c6b.png)

**Comment by ingcsmoreno** [comment]
I think there are a couple of things going on here. There seems to be a bug, that I'll try to fix right away, but also a query issue.

**Comment by ingcsmoreno** [comment]
@grandfatheryun Can you update to this new release: https://github.com/Cruzoft/nbminer-reporter/releases/tag/v1.1.2

and then, on influx, run this query:

```
SELECT mean("hashrate_raw") AS "mean_hashrate_raw" FROM "miner"."miner-device-status" WHERE time > now() - 1h GROUP BY time(:interval:), "friendlyName" FILL(null)
```

**Comment by grandfatheryun** [comment]
it seems still not solve
![image](https://user-images.githubusercontent.com/80371691/144055918-7e8e3e25-46d6-41b6-b809-d178c6ef6ebf.png)

**Comment by ingcsmoreno** [comment]
That's a query issue, not the reporter. you're apply too many filter it matches no data.

Have you tried with the query I sent `SELECT mean("hashrate_raw") AS "mean_hashrate_raw" FROM "miner"."miner-device-status" WHERE time > now() - 1h GROUP BY time(:interval:), "friendlyName" FILL(null)
` ?

**Comment by ingcsmoreno** [comment]
Is the server you sent me the same form the screenshots? It's empty

**Comment by grandfatheryun** [comment]
sorry，sir，i don't know how to use it in cli

**Comment by grandfatheryun** [comment]
can u login in it and check it?
http://106.53.107.206:8086/
user:cyy123
pw:cyy123456

**Comment by ingcsmoreno** [comment]
yes, I was able to login, but I see no data there.

To write the query I sent, yoy can use the `Script Editor`, click that button, and then copy/paste the query I sent in the text box, then click `Submit`.

<img width="575" alt="Screen Shot 2021-11-30 at 10 35 06" src="https://user-images.githubusercontent.com/1449747/144057114-88befc61-82a8-4f5a-8eda-9bc53b06173e.png">

**Comment by grandfatheryun** [comment]
Congratulations, it's works
![image](https://user-images.githubusercontent.com/80371691/144057310-92fb444b-1491-4f95-afaf-e3006f9bc3a7.png)

**Comment by ingcsmoreno** [comment]
Awesome!! Glad to see you get it working! 

And thank a lot for all your feedback!

**Comment by grandfatheryun** [comment]
if ok, i think you can add some function about it shows,like make a page for show the datas

**Comment by ingcsmoreno** [comment]
You mean adding a UI to this app? or some query examples to run on Influx?
