### ISSUE TITLE
can you make a shell for creat the db or make it right for the git

### ISSUE THREAD

**Issue by grandfatheryun** [Cruzoft/nbminer-reporter#5]
well

**Comment by ingcsmoreno** [comment]
You mean the InfluxDB database right?

**Comment by grandfatheryun** [comment]
> 你是说 InfluxDB 数据库吧？

yep，make a shell let it creat the envirment automatic

**Comment by ingcsmoreno** [comment]
@grandfatheryun Check the [InfluxDB Setup](https://github.com/Cruzoft/nbminer-reporter#influxdb-setup) section I've added, let me know if there is something missing.
