### ISSUE TITLE
Some enviornments with high latency or micro connection issues are loosing datapoints

### ISSUE THREAD

**Issue by ingcsmoreno** [Cruzoft/nbminer-reporter#8]
Some environments, shearing the same internet connection, have shown errors trying to reach a remote db, loosing datapoints at different times.

Can we add a sort of retry, or cache to try resending the datapoints in case of a "temporal" connection issue?

**Comment by grandfatheryun** [comment]
resending can allow nbminer like，retry 15s

**Comment by ingcsmoreno** [comment]
Absolutely! Actually I was thinking on a sort of combined solution with a retry, and a local cache to be sure no data points are lost.

**Comment by ingcsmoreno** [comment]
The InfluxDB client already does a retry (check [here](https://github.com/influxdata/influxdb-client-go#handling-of-failed-async-writes) ), so I just added the local memory cache.
